export enum Page {
  LANDING,
  EMPLOYEES_LIST,
  NOTIFICATIONS,
  DEPARTMENT_COURSES,
  MASTER_COURSES,
  PROJECTS,
  SCIENCE,
  CONTACT,
  LOGIN,
  REGISTER,

  // ADMIN

  ADMIN_ACCOUNT_EDIT,
  ADMIN_REGISTER_STUDENT,
  ADMIN_REGISTER_EMPLOYEE,
  ADMIN_COURSES,
  ADMIN_ENGAGEMENT,
  ADMIN_NOTIFICATIONS,
  ADMIN_LANDING,

  // Professor

  PROFESSOR_COURSES,
  PROFESSOR_COURSE_NOTIFICATIONS,
  PROFESSOR_REGISTRATION_LISTS,
  PROFESSOR_LANDING,

  // STUDENT

  STUDENT_LANDING,
  STUDENT_COURSE_PICKER,
  STUDENT_MY_COURSES,
  STUDENT_REG_LSIT,
  STUDENT_PASSWORD_CHANGE,
}
